server:
  port: 8081

spring:
  application:
    name: odu-processor
  datasource:
    url: jdbc:h2:mem:odudb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console